### ISSUE TITLE
Missing enclosure instructions and part-list

### ISSUE THREAD

**Issue by wonder76** [dheera/big-yellow-proxxon-mf70-conversion#1]
That would be great to have build instructions for the enclosure and a part-list too...

**Comment by dheera** [comment]
Hi,
It's based on 20cm aluminum extrusions which I cut with a miter saw, tapped, and put together with off-the-shelf fasteners. 8020 Inc sells these ("2020 series") but there are also a lot of much cheaper China-made extrusions you can get which are just fine and save a lot of money, just that the fasteners are not always cross-compatible with the 8020 stuff so make sure you get the right fasteners for those.

The panels are polycarbonate ("lexan") which I got custom cut at TAP Plastics if you're in the bay area. Do NOT use acrylic, it can shatter and crack easily if a high speed projectile like a milling bit hits it.

**Comment by wonder76** [comment]
thx a lot!
